app.version=${appVersion}
app.channel=${appChannel}
github.owner=blackarcadia
github.repo=axial-client
github.asset=AxialLauncher.app.zip
github.asset.mac=AxialLauncher.app.zip
github.asset.windows=AxialLauncher-windows.zip
