plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
}

group = 'com.axial.cosmetics'
version = '1.1.0'

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net' }
}

dependencies {
    minecraft 'com.mojang:minecraft:1.21.11'
    mappings "net.fabricmc:yarn:1.21.11+build.2:v2"
    modImplementation 'net.fabricmc:fabric-loader:0.18.1'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.141.3+1.21.11'
    include implementation('net.raphimc:MinecraftAuth:5.0.0')
    compileOnly files('../src/main/resources/axialutils-1.0-SNAPSHOT.jar')
    implementation 'com.google.code.gson:gson:2.11.0'
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    // Use the current JDK but target Java 21 bytecode/runtime
    withSourcesJar()
}
